version: '3.7'

services:
  angular:
    container_name: ui
    build:
      context: /home/vlad/Diplom/UI/
      dockerfile: Dockerfile
    volumes:
      - ./ui:/app
      - /app/node_modules
    ports:
      - "80:80"
      - "443:443"

  csharp:
    container_name: backend
    build:
      context: /home/vlad/Diplom/
      dockerfile: Dockerfile
    volumes:
      - ./sqlite-data/company.db:/app/company.db
    ports:
      - "65204:8080"

  # db:
  #   container_name: db
  #   image: keinos/sqlite3:latest
  #   restart: always
  #   volumes:
  #     - ./sqlite-data1:/var/lib/sqlite

volumes:
  sqlite-data: